### ISSUE TITLE
diagnostics app: Closed. Original cause [Error: [429] Maximum active concurrent connections limit has been reached undefined].

### ISSUE THREAD

**Issue by Dieterbe** [powersync-ja/powersync-service#82] opened 2024-09-15 20:17 UTC
i regularly run into this issue when trying to use the diagnostics app (https://diagnostics-app.powersync.com/login) against my local docker stack.
the docker stack seems to work fine, it's a pretty basic setup, without much load. based on the django standalone demo

the logs don't show anything revealing:
```
powersync-1  | {"level":"info","message":"powersync_2_d37f replicating op 2443200 00000001/3E79F820","timestamp":"2024-09-15T17:39:09.490Z"}
powersync-1  | {"level":"info","message":"powersync_2_d37f replicating op 2443300 00000001/3E85A570","timestamp":"2024-09-15T17:39:09.661Z"}
powersync-1  | {"level":"info","message":"powersync_2_d37f replicating op 2443400 00000001/3E9007F0","timestamp":"2024-09-15T17:39:09.834Z"}
powersync-1  | {"level":"info","message":"powersync_2_d37f replicating op 2443500 00000001/3E9A64B8","timestamp":"2024-09-15T17:39:10.006Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:29:16.795Z"}
powersync-1  | {"duration_ms":187791,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T19:32:24.577Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:36:07.027Z"}
powersync-1  | {"duration_ms":88681,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T19:37:35.702Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:37:45.263Z"}
powersync-1  | {"duration_ms":298674,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T19:42:43.934Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:42:43.941Z"}
powersync-1  | {"duration_ms":280846,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T19:47:24.785Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:47:24.793Z"}
powersync-1  | {"duration_ms":260215,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T19:51:45.005Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:51:45.010Z"}
powersync-1  | {"duration_ms":290877,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T19:56:35.884Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T19:56:35.889Z"}
powersync-1  | {"duration_ms":280118,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T20:01:16.005Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T20:01:16.010Z"}
powersync-1  | {"duration_ms":279997,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T20:05:56.004Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T20:05:56.009Z"}
powersync-1  | {"duration_ms":279998,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T20:10:36.005Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T20:10:36.011Z"}
powersync-1  | {"duration_ms":259998,"level":"info","message":"POST /sync/stream","method":"POST","path":"/sync/stream","route":"/sync/stream","status":200,"timestamp":"2024-09-15T20:14:56.005Z"}
powersync-1  | {"level":"info","message":"New checkpoint: 38 | write: null | buckets: 2 [\"global[]\",\"user_lists[4]\"]","timestamp":"2024-09-15T20:14:56.009Z"}
```

![image](https://github.com/user-attachments/assets/12d6d6fc-aca2-4048-9196-6db9edff0d46)

**Comment by stevensJourney** [comment] 2024-09-16 06:34
Does this happen while co-developing with a certain client SDK or is it only from continued (multiple reconnects) use of the diagnostics application?

**Comment by Dieterbe** [comment] 2024-09-16 08:55
I have tried to connect with diagnostic app several times (from a single tab) and failed. At the same time I'm testing a dart/flutter app that is connected. Usually after a bunch of attempts it will start working again.

**Comment by stevensJourney** [comment] 2024-09-17 08:53
I could not reproduce this on my side. This might have been an issue in older versions of the PowerSync Service Docker image. Can you confirm you are using the latest version of the PowerSync image, `0.5.4`?

**Comment by Dieterbe** [comment] 2024-09-17 12:31
this was with `journeyapps/powersync-service   latest      3f06e9aaea9d   8 days ago     285MB`

**Comment by stevensJourney** [comment] 2024-09-18 07:28
That's interesting. I'm not sure why those digests seem different... The latest image should log the current number of active web socket connections. There should be log entries of the form `Currently have [number] active WebSocket connection(s)`. Do you currently see logs like that? If those logs are missing I get the feeling the container is not using the latest image. 

Another way to confirm the version of the PowerSync service is to run `cat service/package.json` inside the container. The `version` should relate to the image version. Could you please confirm the output?

**Comment by Dieterbe** [comment] 2024-09-18 11:36
ok still using the "latest" image, 3f06e9aaea9d

```
web@4ca2e64f70d7:/app$ cat service/package.json 
{
  "name": "@powersync/service-image",
  "version": "0.5.4",
(...)
```
i also see `"Currently have 1 active WebSocket connection(s)"` messages.
right now i don't have time to do the full stack testing again however with my flutter app and with the diagnostics app. let me know what else you need.

**Comment by stevensJourney** [comment] 2024-09-26 07:22
I've tried to reproduce this, but have not been successful. 

Could you please share what kind of error you were receiving when trying to connect (and failing) to the Diagnostics app?

It would be very helpful if you could monitor the service logs and share which error causes the number of active WebSocket connections to increase on your side.

**Comment by stevensJourney** [comment] 2024-10-17 07:49
Closing this issue for now since I could not reproduce this. Feel free to reopen with steps to reproduce.

**Closed by stevensJourney** 2024-10-17 07:49 UTC
